services:
  ai-publisher:
    build: .
    container_name: phase2-ai
    env_file:
      - .env
    ports:
      - "3001:3000"
    networks:
      - beyondchats-net



networks:
  beyondchats-net:
    external: true
